version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=piwik
      - MYSQL_USER=piwik
      - MYSQL_PASSWORD=password
    volumes:
      - ./database:/var/lib/mysql

  piwik:
    image: piwik:fpm
  links:
      - db
    ports:
      - 9000:9000
    volumes:
      - ./config:/var/www/html/config:rw
      - ./scripts:/scripts:ro
    command: /scripts/piwik-init.sh

  web:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - piwik
    environment:
      - VIRTUAL_HOST
