version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=piwik
      - MYSQL_USER=piwik
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./resources:/docker-entrypoint-initdb.d/
  piwik:
    environment:
      - DB_DATABASE=piwik
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=piwik
      - DB_PASSWORD=password
    image: piwik:fpm
    links:
      - db
    depends_on:
      - db
    volumes:
      #- ./config:/var/www/html/config:rw
      - ./scripts:/scripts:ro
    command: php-fpm
    entrypoint: /scripts/piwik-entrypoint.sh
  web:
    image: nginx:alpine
    links:
      - piwik
    depends_on:
      - piwik
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST
    ports:
      - "9001:80"
